namespace Executorlibs.Huya.Protocol.Models
{
    public enum HuyaMsgType : byte
    {
        Null = 0,
        RegisterRequest = 1,
        RegisterResponse = 2,
        WupRequest = 3,
        WupResponse = 4,
        HeartBeat = 5,
        HeartBeatAck = 6,
        MsgPushRequest = 7,
        DeregisterRequest = 8,
        DeRegisterResponse = 9,
        VerifyCookieRequest = 10,
        VerifyCookieResponse = 11,
        VerifyHuyaTokenRequest = 12,
        VerifyHuyaTokenResponse = 13,
        UnVerifyRequest = 14,
        UnVerifyResponse = 15,
        RegisterGroupRequest = 16,
        RegisterGroupResponse = 17,
        UnRegisterGroupRequest = 18,
        UnRegisterGroupResponse = 19,
        HeartBeatRequest = 20,
        HeartBeatResponse = 21,
        MsgPushRequestv2 = 22,
        UpdateUserExpsRequest = 23,
        UpdateUserExpsResponse = 24,
        WsHistoryMsgRequest = 25,
        WSHistoryMsgResponse = 26,
        EnterP2P = 27,
        EnterP2PAck = 28,
        ExitP2P = 29,
        ExitP2PAck = 30,
        SyncGroupRequest = 31,
        SyncGroupResponse = 32,
        UpdateUserInfoRequest = 33,
        UpdateUserInfoResponse = 34,
        MsgAckRequest = 35,
        MsgAckResponse = 36,
        CloudGameRequest = 37,
        CloudGamePush = 38,
        CloudGameResponse = 39
    }
}
